### ISSUE TITLE
[BUG] Infinite amount

### ISSUE THREAD

**Issue by nichiporenko** [antonTroyan/ELeornio#1]
I can click an infinite amount of times on a right answer and the counter will always increment its value:

![image](https://user-images.githubusercontent.com/10104739/150513636-0141caa8-6137-4642-9f98-5b22b904e306.png)

**Comment by nichiporenko** [comment]
Thanks for your time spent reading this!

**Comment by antonTroyan** [comment]
Maybe you can do it by yourself?) I feel that you are an experienced proger)

**Comment by nichiporenko** [comment]
Yes, my price is 300$/hour

**Comment by antonTroyan** [comment]
How about more?) I heard that GB provide citizenship for those who contribute in opensource

**Comment by nichiporenko** [comment]
I already contributed to opensource:
![image](https://user-images.githubusercontent.com/10104739/150526187-6e993582-f412-405a-969e-5e4d921916f9.png)

**Comment by antonTroyan** [comment]
Doesn't think that it will be enough for Queen)

**Comment by antonTroyan** [comment]
Bug was fixed. Invoice with standard price [multiplied x10 because of urgency] will be send to your email.
